### ISSUE TITLE
Redactor Lizenz

### ISSUE THREAD

**Issue by skerbis** [aeberhard/redactor#2]
Hallo Andreas, 

wie sieht es mit der Lizenz aus? Kann ich den Editor nutzen oder muss ich eine eigene Lizenz besorgen?

**Comment by polarpixel** [comment]
Ich hatte eine Developer Lizenz gekauft und für Redaxo gestiftet.
Kannst also so nutzen.

**Comment by skerbis** [comment]
Super!. Dann teste ich das mal :-). ---> Wie kann ich mich bedanken? Hast Du sowas wie eine AMAZON-Wunschliste oder so?

**Comment by polarpixel** [comment]
Ist ja lieb, aber musst Du nicht.
Feedback, Anregungen oder bei Interesse Mitarbeit ist immer am besten. :-)

Wobei ich gestehen muss, ich nutze ja selbst eigentlich immer nur Markitup. Aber von den WYSIWYG-Editoren fand ich den sehr ansprechend.

**Comment by skerbis** [comment]
Alles klar! Wird gemacht. :+1: )
